#
###################################
# Site wide configuration
####################################
#
title: Charles Lewis
email: charlesslewis10@gmail.com
description: A collection of projects
url: http://clewis.cc
keywords: ["blog", "jekyll", "cyber", "security", "cybersecurity", "charles", "lewis"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          America/Seattle
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Charles Lewis
  avatar: leonids-logo.png
  job: "Cybersecurity Engineer"
  bio: "A simple security engineer and producer."
  email: charlesslewis10@gmail.com
  disqus-shortname:
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: clewis10
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: charles-lewis-b2a12a140
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: charlessssssssss
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  reddit: #username
  telegram: #username
